DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT EXISTS "users" (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "todos" (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	todo TEXT NOT NULL,
	user_id	INTEGER NOT NULL,
	deadline DATE,
	done INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY("user_id") REFERENCES "users"("id")
);
